export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: string;
  subCategory?: string;
  spiceLevel: number;
  isVeg: boolean;
  isSpecial: boolean;
  cookTime: string;
  rating: number;
  allergens?: string[];
  nutritionalInfo?: {
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
  };
}

export const menuCategories = [
  "All Items",
  "Signature Biryanis",
  "Clay Pot Specialties",
  "Non-Veg Kolambus",
  "Chicken Varieties",
  "Mutton Delights",
  "Seafood",
  "Starters & Appetizers",
  "Rice Varieties",
  "Vegetarian",
  "Traditional Beverages",
  "Desserts",
];

export const menuItems: MenuItem[] = [
  // Biryanis
  {
    id: "1",
    name: "Naatu Koli Biryani",
    description: "Country chicken biryani cooked in traditional clay pot with aromatic spices and basmati rice",
    price: 450,
    image: "/images/dishes/6naatu koli biriyani.jpg",
    category: "Signature Biryanis",
    spiceLevel: 3,
    isVeg: false,
    isSpecial: true,
    cookTime: "45 mins",
    rating: 4.9,
  },
  {
    id: "2",
    name: "Mutton Biryani",
    description: "Tender mutton pieces layered with fragrant basmati rice and special biryani masala",
    price: 520,
    image: "/images/dishes/mutton biriYANI.jpg",
    category: "Signature Biryanis",
    spiceLevel: 3,
    isVeg: false,
    isSpecial: true,
    cookTime: "50 mins",
    rating: 4.8,
  },

  // Chicken Varieties
  {
    id: "3",
    name: "Pallipalayam Chicken",
    description: "Famous dry chicken dish from Pallipalayam with unique spice blend and curry leaves",
    price: 380,
    image: "/images/dishes/14pallipalayam chicken.jpg",
    category: "Chicken Varieties",
    spiceLevel: 4,
    isVeg: false,
    isSpecial: false,
    cookTime: "35 mins",
    rating: 4.8,
  },
  {
    id: "4",
    name: "Chicken Varuval",
    description: "Spicy dry chicken fry with traditional South Indian masala",
    price: 350,
    image: "/images/dishes/17chicken varuval.jpg",
    category: "Chicken Varieties",
    spiceLevel: 4,
    isVeg: false,
    isSpecial: false,
    cookTime: "30 mins",
    rating: 4.7,
  },
  {
    id: "5",
    name: "Chilli Chicken",
    description: "Indo-Chinese style chicken with bell peppers and spicy sauce",
    price: 360,
    image: "/images/dishes/9 chill chicken.jpg",
    category: "Chicken Varieties",
    spiceLevel: 3,
    isVeg: false,
    isSpecial: false,
    cookTime: "25 mins",
    rating: 4.6,
  },
  {
    id: "6",
    name: "Chicken Fry",
    description: "Crispy fried chicken with aromatic spices",
    price: 340,
    image: "/images/dishes/17 chicken fry.jpg",
    category: "Chicken Varieties",
    spiceLevel: 3,
    isVeg: false,
    isSpecial: false,
    cookTime: "25 mins",
    rating: 4.6,
  },
  {
    id: "7",
    name: "Chest Bone Fry",
    description: "Crispy fried chicken chest pieces with special masala",
    price: 320,
    image: "/images/dishes/10chest bone fry.jpg",
    category: "Chicken Varieties",
    spiceLevel: 3,
    isVeg: false,
    isSpecial: false,
    cookTime: "25 mins",
    rating: 4.5,
  },
  {
    id: "8",
    name: "Chest Bone Gravy",
    description: "Chicken chest pieces in rich, flavorful gravy",
    price: 340,
    image: "/images/dishes/11chest bone gravy.jpg",
    category: "Chicken Varieties",
    spiceLevel: 2,
    isVeg: false,
    isSpecial: false,
    cookTime: "30 mins",
    rating: 4.5,
  },

  // Mutton Delights
  {
    id: "9",
    name: "Mutton Chops",
    description: "Tender mutton chops marinated in special masala and grilled to perfection",
    price: 580,
    image: "/images/dishes/Mutton chops - Copy.jpg",
    category: "Mutton Delights",
    spiceLevel: 4,
    isVeg: false,
    isSpecial: true,
    cookTime: "40 mins",
    rating: 4.9,
  },
  {
    id: "10",
    name: "Nalli Kulambu",
    description: "Slow-cooked goat trotters in thick, spicy gravy",
    price: 420,
    image: "/images/dishes/5nalli kulambu.jpg",
    category: "Mutton Delights",
    spiceLevel: 3,
    isVeg: false,
    isSpecial: false,
    cookTime: "60 mins",
    rating: 4.7,
  },
  {
    id: "11",
    name: "Kadai Fry",
    description: "Mutton pieces stir-fried with onions and spices in a kadai",
    price: 450,
    image: "/images/dishes/13kadai fry.jpg",
    category: "Mutton Delights",
    spiceLevel: 4,
    isVeg: false,
    isSpecial: false,
    cookTime: "35 mins",
    rating: 4.6,
  },
  {
    id: "12",
    name: "Leg Gravy",
    description: "Goat leg pieces cooked in rich, aromatic gravy",
    price: 480,
    image: "/images/dishes/15leg gravy.jpg",
    category: "Mutton Delights",
    spiceLevel: 3,
    isVeg: false,
    isSpecial: false,
    cookTime: "45 mins",
    rating: 4.7,
  },
  {
    id: "13",
    name: "Brain Fry",
    description: "Goat brain delicacy fried with special spices",
    price: 380,
    image: "/images/dishes/1brain.jpg",
    category: "Mutton Delights",
    spiceLevel: 2,
    isVeg: false,
    isSpecial: false,
    cookTime: "20 mins",
    rating: 4.4,
  },
  {
    id: "14",
    name: "Liver Fry",
    description: "Goat liver pieces fried with onions and spices",
    price: 360,
    image: "/images/dishes/3liver fry.jpg",
    category: "Mutton Delights",
    spiceLevel: 3,
    isVeg: false,
    isSpecial: false,
    cookTime: "25 mins",
    rating: 4.5,
  },

  // Seafood
  {
    id: "15",
    name: "Vanjaram Fish Varuval",
    description: "King fish fry with traditional South Indian spices",
    price: 420,
    image: "/images/dishes/vanjaram meen varuval.jpg",
    category: "Seafood",
    spiceLevel: 3,
    isVeg: false,
    isSpecial: false,
    cookTime: "25 mins",
    rating: 4.7,
  },
  {
    id: "16",
    name: "Fish Fry",
    description: "Crispy fried fish with coastal spices",
    price: 380,
    image: "/images/dishes/21fish fry.jpg",
    category: "Seafood",
    spiceLevel: 3,
    isVeg: false,
    isSpecial: false,
    cookTime: "20 mins",
    rating: 4.6,
  },
  {
    id: "17",
    name: "Prawn Masala",
    description: "Fresh prawns cooked in rich coconut gravy with curry leaves",
    price: 460,
    image: "/images/dishes/18prawn.jpg",
    category: "Seafood",
    spiceLevel: 2,
    isVeg: false,
    isSpecial: false,
    cookTime: "20 mins",
    rating: 4.6,
  },
  {
    id: "18",
    name: "Chilli Fish",
    description: "Fish pieces in Indo-Chinese style with peppers and spicy sauce",
    price: 400,
    image: "/images/dishes/chilly fish - Copy.jpg",
    category: "Seafood",
    spiceLevel: 3,
    isVeg: false,
    isSpecial: false,
    cookTime: "25 mins",
    rating: 4.5,
  },
  {
    id: "19",
    name: "Nethili Fish Fry",
    description: "Crispy fried anchovies with traditional spices",
    price: 280,
    image: "/images/dishes/nethili fish.jpg",
    category: "Seafood",
    spiceLevel: 2,
    isVeg: false,
    isSpecial: false,
    cookTime: "15 mins",
    rating: 4.4,
  },

  // Rice Varieties
  {
    id: "20",
    name: "Chicken Fried Rice",
    description: "Wok-tossed rice with tender chicken pieces and vegetables",
    price: 320,
    image: "/images/dishes/26chicken fried rice.jpg",
    category: "Rice Varieties",
    spiceLevel: 1,
    isVeg: false,
    isSpecial: false,
    cookTime: "15 mins",
    rating: 4.5,
  },
  {
    id: "21",
    name: "Mushroom Fried Rice",
    description: "Fragrant fried rice with fresh mushrooms and vegetables",
    price: 280,
    image: "/images/dishes/27mushroom fried rice.jpg",
    category: "Rice Varieties",
    spiceLevel: 1,
    isVeg: true,
    isSpecial: false,
    cookTime: "15 mins",
    rating: 4.4,
  },
  {
    id: "22",
    name: "Veg Fried Rice",
    description: "Colorful vegetable fried rice with aromatic spices",
    price: 260,
    image: "/images/dishes/25veg fried rice.jpg",
    category: "Rice Varieties",
    spiceLevel: 1,
    isVeg: true,
    isSpecial: false,
    cookTime: "15 mins",
    rating: 4.3,
  },

  // Starters & Appetizers
  {
    id: "23",
    name: "Kothu Parotta",
    description: "Shredded parotta mixed with chicken, eggs and spices",
    price: 280,
    image: "/images/dishes/2kothu.jpg",
    category: "Starters & Appetizers",
    spiceLevel: 3,
    isVeg: false,
    isSpecial: false,
    cookTime: "20 mins",
    rating: 4.6,
  },
  {
    id: "24",
    name: "Thalakari Soup",
    description: "Traditional goat head soup with aromatic spices",
    price: 180,
    image: "/images/dishes/20 thalakari.jpg",
    category: "Starters & Appetizers",
    spiceLevel: 2,
    isVeg: false,
    isSpecial: false,
    cookTime: "15 mins",
    rating: 4.5,
  },

  // Vegetarian
  {
    id: "25",
    name: "Gobi Fry",
    description: "Crispy fried cauliflower with spices",
    price: 220,
    image: "/images/dishes/22 gobi fry.jpg",
    category: "Vegetarian",
    spiceLevel: 2,
    isVeg: true,
    isSpecial: false,
    cookTime: "15 mins",
    rating: 4.3,
  },
  {
    id: "26",
    name: "Veg Meals",
    description: "Complete South Indian vegetarian meal with variety of dishes",
    price: 180,
    image: "/images/dishes/veg meals.jpg",
    category: "Vegetarian",
    spiceLevel: 1,
    isVeg: true,
    isSpecial: false,
    cookTime: "10 mins",
    rating: 4.5,
  },

  // Clay Pot Specialties
  {
    id: "27",
    name: "Country Chicken Curry",
    description: "Traditional country chicken curry slow-cooked in clay pot",
    price: 420,
    image: "/images/dishes/country chicken  - Copy.jpg",
    category: "Clay Pot Specialties",
    spiceLevel: 3,
    isVeg: false,
    isSpecial: true,
    cookTime: "45 mins",
    rating: 4.8,
  },
  {
    id: "28",
    name: "Mutton Kothukari",
    description: "Spicy dry mutton curry cooked in clay pot with special masala",
    price: 480,
    image: "/images/dishes/mutton kothukari - Copy.jpg",
    category: "Clay Pot Specialties",
    spiceLevel: 4,
    isVeg: false,
    isSpecial: true,
    cookTime: "50 mins",
    rating: 4.7,
  },
  {
    id: "29",
    name: "Kudal Kolambu",
    description: "Traditional intestine curry slow-cooked in clay pot",
    price: 380,
    image: "/images/dishes/kudal kolambu - Copy - Copy.jpg",
    category: "Clay Pot Specialties",
    spiceLevel: 3,
    isVeg: false,
    isSpecial: false,
    cookTime: "40 mins",
    rating: 4.5,
  },
  {
    id: "30",
    name: "Aatukaal Paaya",
    description: "Goat trotters soup slow-cooked overnight in clay pot",
    price: 350,
    image: "/images/dishes/aatukaal paaya - Copy - Copy (2) - Copy.jpg",
    category: "Clay Pot Specialties",
    spiceLevel: 2,
    isVeg: false,
    isSpecial: true,
    cookTime: "60 mins",
    rating: 4.8,
  },
];